services:
  pdf-service:
    build: .
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - pdfgen
  cloudflared-tunnel:
    container_name: pdfgen-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - pdfgen
    env_file: "./.env"
networks:
  pdfgen:
    driver: bridge